import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync,symlinkSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {generateSecretKey,getPublicKey} from 'nostr-tools/pure';
import {startFederationService,readFederationConfig} from '../src/federation-service.mjs';
function fixture(){const root=mkdtempSync(join(tmpdir(),'fed-service-'));const workspaces=['alpha','beta'].map(id=>{writeFileSync(join(root,id+'.key'),Buffer.from(generateSecretKey()).toString('hex'),{mode:0o600});return {id,audience:id,controllerPubkey:getPublicKey(generateSecretKey()),verifierPubkeys:[getPublicKey(generateSecretKey())],workerPolicies:[{pubkey:getPublicKey(generateSecretKey()),capabilities:['sum'],cost:1}],transportSecretKeyFile:id+'.key'};});return {root,config:{stateRoot:'state',relayUrl:'wss://relay.example',workspaces}};}
test('launcher creates isolated authorities and closes every resource once',async()=>{const f=fixture();let registryCloses=0;const closed=[],started=[];try{const service=await startFederationService(f.config,{baseDirectory:f.root,registryFactory:config=>{assert.equal(config.workspaces.length,2);assert.equal(JSON.stringify(config).includes('secretKey'),false);return {close:()=>registryCloses++};},authorityFactory:async options=>{started.push(options.workspace);return {close:()=>closed.push(options.workspace)};}});assert.deepEqual(started,['alpha','beta']);assert.equal(service.workspaces.length,2);await service.close();await service.close();assert.deepEqual(closed,['alpha','beta']);assert.equal(registryCloses,1);}finally{rmSync(f.root,{recursive:true,force:true});}});
test('partial startup failure releases earlier authority and registry',async()=>{const f=fixture();let closed=0;try{await assert.rejects(startFederationService(f.config,{baseDirectory:f.root,registryFactory:()=>({close:()=>closed++}),authorityFactory:async({workspace})=>{if(workspace==='beta')throw Error('unreachable');return {close:()=>closed++};}}),/unreachable/);assert.equal(closed,2);}finally{rmSync(f.root,{recursive:true,force:true});}});
test('rejects unsafe relay, symlink keys, exposed config and duplicate roles before connecting',async()=>{const f=fixture();try{await assert.rejects(startFederationService({...f.config,relayUrl:'ws://relay.example'},{baseDirectory:f.root}),/TLS/);symlinkSync(join(f.root,'alpha.key'),join(f.root,'link.key'));f.config.workspaces[0].transportSecretKeyFile='link.key';await assert.rejects(startFederationService(f.config,{baseDirectory:f.root}));writeFileSync(join(f.root,'config.json'),JSON.stringify(f.config),{mode:0o644});assert.throws(()=>readFederationConfig(join(f.root,'config.json')),/owner-only/);f.config.workspaces[0].transportSecretKeyFile='alpha.key';f.config.workspaces[0].verifierPubkeys=[f.config.workspaces[0].controllerPubkey];await assert.rejects(startFederationService(f.config,{baseDirectory:f.root}),/separate/);}finally{rmSync(f.root,{recursive:true,force:true});}});
