import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {createTaskApi} from '../src/task-api.mjs';
import {startTaskApiServer} from '../src/task-api-server.mjs';

function fixture(){const all=new Map();const calls=[];const request=async(op,data)=>{calls.push({op,data});if(op==='submit'){all.set(data.id,{spec:data,status:'queued',epoch:1,attempts:0,spent:0});return {taskId:data.id,status:'queued'};}if(op==='task_get')return {task:all.get(data.taskId)};if(op==='cancel'){all.get(data.taskId).status='cancelled';return {status:'cancelled'};}if(op==='task_list')return {tasks:[...all.values()].map(t=>({taskId:t.spec.id,status:t.status,capability:t.spec.capability,secret:'never leak'})),nextCursor:null};throw Error('unexpected');};return {all,calls,request,api:createTaskApi({request,workspace:'alpha',agentUrl:'http://127.0.0.1/a2a'})};}
const spec={id:'task1',capability:'sum',input:{secret:'private'},vector:[1,0],budget:3,deadlineMs:Date.now()+60000};
const rpc=(method,params)=>({jsonrpc:'2.0',id:1,method,params});
test('MCP real protocol lists and calls workspace tools, no secret status fields',async()=>{const f=fixture(),server=f.api.createMcpServer(),client=new Client({name:'test',version:'1'});const [a,b]=InMemoryTransport.createLinkedPair();await server.connect(a);await client.connect(b);try{const tools=await client.listTools();assert.equal(tools.tools.length,5);const submit=await client.callTool({name:'task_submit',arguments:spec});assert.equal(submit.isError,undefined);const result=await client.callTool({name:'task_get',arguments:{taskId:spec.id}});assert.equal(JSON.stringify(result).includes('private'),false);const artifact=await client.callTool({name:'artifact_get',arguments:{taskId:spec.id}});assert.equal(artifact.isError,true);assert.equal(f.calls.some(c=>c.op==='status'),false);}finally{await client.close();await server.close();}});
test('verified artifact requires matching hash, epoch and acceptance',async()=>{const f=fixture();await f.api.task_submit(spec);const t=f.all.get(spec.id);t.status='completed';t.artifact={answer:3};t.artifactHash=createHash('sha256').update(JSON.stringify(t.artifact)).digest('hex');t.verification={accepted:true,epoch:1,artifactHash:t.artifactHash};assert.equal((await f.api.artifact_get({taskId:spec.id})).artifact.answer,3);t.artifact.answer=4;await assert.rejects(f.api.artifact_get({taskId:spec.id}),/unavailable/);t.artifact.answer=3;t.verification.epoch=0;await assert.rejects(f.api.artifact_get({taskId:spec.id}),/unavailable/);});
test('A2A subset sends gets cancels and rejects unsupported and malformed calls',async()=>{const f=fixture();const sent=await f.api.a2a(rpc('message/send',{message:{kind:'message',role:'user',messageId:'m1',parts:[{kind:'data',data:spec}]}}));assert.equal(sent.result.status.state,'submitted');assert.equal((await f.api.a2a(rpc('tasks/get',{id:spec.id}))).result.id,spec.id);assert.equal((await f.api.a2a(rpc('tasks/cancel',{id:spec.id}))).result.status.state,'canceled');assert.equal((await f.api.a2a(rpc('message/stream',{}))).error.code,-32601);assert.equal((await f.api.a2a(rpc('tasks/get',{id:'missing'}))).error.code,-32001);assert.equal((await f.api.a2a(rpc('tasks/get',{id:spec.id,workspace:'other'}))).error.code,-32602);assert.equal((await f.api.a2a({})).error.code,-32600);});
test('pagination and submission reject tenant injection and unbounded values',async()=>{const f=fixture();for(const limit of [0,-1,101,Infinity,NaN,1.5])await assert.rejects(f.api.task_list({limit}));await assert.rejects(f.api.task_submit({...spec,workspace:'other'}));await f.api.task_submit(spec);const result=await f.api.task_list({limit:1});assert.equal(JSON.stringify(result).includes('never leak'),false);});
test('HTTP auth, origin checks, console and actual MCP over HTTP',async()=>{const f=fixture();const service=await startTaskApiServer({resolveRequest:async req=>req.headers.authorization==='Bearer test'?{request:f.request,workspace:'alpha'}:null});try{assert.equal((await fetch(service.url+'/agent-card')).status,200);assert.equal((await fetch(service.url+'/console')).status,200);assert.equal((await fetch(service.url+'/a2a',{method:'POST'})).status,401);assert.equal((await fetch(service.url+'/a2a',{method:'POST',headers:{origin:'https://evil.example',authorization:'Bearer test'}})).status,403);const client=new Client({name:'http-test',version:'1'});await client.connect(new StreamableHTTPClientTransport(new URL(service.url+'/mcp'),{requestInit:{headers:{authorization:'Bearer test'}}}));try{assert.equal((await client.listTools()).tools.length,5);assert.equal((await client.callTool({name:'task_submit',arguments:spec})).isError,undefined);}finally{await client.close();}const response=await fetch(service.url+'/a2a',{method:'POST',headers:{authorization:'Bearer test','content-type':'application/json'},body:JSON.stringify(rpc('tasks/get',{id:spec.id}))});assert.equal((await response.json()).result.id,spec.id);}finally{await service.close();}});
test('workspace clients never allow task identity to select another workspace',async()=>{const a=fixture(),b=fixture();await a.api.task_submit(spec);await b.api.task_submit({...spec,input:{secret:'workspace-b'}});assert.equal((await a.api.task_get({taskId:spec.id})).status,'queued');await a.api.task_cancel({taskId:spec.id});assert.equal((await b.api.task_get({taskId:spec.id})).status,'queued');await assert.rejects(a.api.task_get({taskId:spec.id,workspace:'b'}));assert.equal(a.calls.some(c=>Object.hasOwn(c.data,'workspace')),false);});
test('HTTP body bounds, public metadata and unsupported A2A do not disclose private inputs',async()=>{const f=fixture();const service=await startTaskApiServer({resolveRequest:async()=>({request:f.request,workspace:'alpha'})});try{const card=await (await fetch(service.url+'/.well-known/agent-card.json')).json();assert.equal(card.protocolVersion,'0.3.0');assert.equal(card.capabilities.streaming,false);const response=await fetch(service.url+'/api/task_submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...spec,input:'x'.repeat(40000)})});assert.equal(response.status,413);assert.equal(f.calls.length,0);const script=await (await fetch(service.url+'/console.js')).text();assert.equal(script.includes('innerHTML'),false);assert.equal(script.includes('localStorage'),false);}finally{await service.close();}});
