import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync,chmodSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {generateSecretKey,getPublicKey,verifyEvent} from 'nostr-tools/pure';
import {createExecutionServer} from '../src/service.mjs';
import {startTaskService,readTaskServiceConfig} from '../src/task-service.mjs';
const post=(url,token,name,data)=>fetch(url+'/api/'+name,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(data)});
test('configured task service signs controller requests and authenticates every HTTP call',async()=>{
 const root=mkdtempSync(join(tmpdir(),'task-service-')),key=generateSecretKey(),token='a'.repeat(48),tasks=new Map();
 const execution=createExecutionServer({execute:event=>{assert(verifyEvent(event));assert.equal(event.pubkey,getPublicKey(key));assert.deepEqual(event.tags,[['d','workspace-alpha']]);const {op,data}=JSON.parse(event.content);if(op==='submit'){tasks.set(data.id,{spec:data,status:'queued',epoch:1});return {taskId:data.id,status:'queued'};}if(op==='task_get')return {task:tasks.get(data.taskId)};if(op==='task_list')return {tasks:[...tasks.values()].map(t=>({taskId:t.spec.id,status:t.status})),nextCursor:null};if(op==='cancel'){tasks.get(data.taskId).status='cancelled';return {status:'cancelled'};}throw Error('unexpected');}});
 let service;try{const port=await execution.listen();writeFileSync(join(root,'key'),Buffer.from(key).toString('hex'),{mode:0o600});writeFileSync(join(root,'token'),token,{mode:0o600});const config={workspaces:[{id:'alpha',audience:'workspace-alpha',controllerSecretKeyFile:'key',coordinatorUrl:`http://127.0.0.1:${port}`,tokenFile:'token',scopes:['task:read','task:submit','task:cancel']}]};writeFileSync(join(root,'config.json'),JSON.stringify(config),{mode:0o600});service=await startTaskService(readTaskServiceConfig(join(root,'config.json')),{baseDirectory:root});const spec={id:'t1',capability:'sum',input:{a:1},vector:[1],budget:1,deadlineMs:Date.now()+10000};assert.equal((await post(service.url,'wrong','task_submit',spec)).status,401);assert.equal((await post(service.url,token,'task_submit',spec)).status,200);assert.equal((await (await post(service.url,token,'task_get',{taskId:'t1'})).json()).status,'queued');assert.equal((await (await post(service.url,token,'task_cancel',{taskId:'t1'})).json()).status,'cancelled');assert.equal((await post(service.url,token,'task_get',{taskId:'t1',workspace:'beta'})).status,400);}finally{await service?.close();await execution.close();rmSync(root,{recursive:true,force:true});}
});
test('read-only default prevents writes and credential permissions are enforced',async()=>{const root=mkdtempSync(join(tmpdir(),'task-service-'));let service;try{writeFileSync(join(root,'key'),'01'.repeat(32),{mode:0o600});writeFileSync(join(root,'token'),'b'.repeat(48),{mode:0o600});const config={workspaces:[{id:'alpha',audience:'alpha',controllerSecretKeyFile:'key',coordinatorUrl:'http://127.0.0.1:1',tokenFile:'token'}]};let called=false;service=await startTaskService(config,{baseDirectory:root,requestFactory:()=>async()=>{called=true;return {};}});const response=await post(service.url,'b'.repeat(48),'task_submit',{id:'t1',capability:'sum',input:1,vector:[1],budget:1,deadlineMs:Date.now()+10000});assert.equal(response.status,400);assert.equal(called,false);chmodSync(join(root,'token'),0o644);await assert.rejects(startTaskService(config,{baseDirectory:root}),/owner-only/);}finally{await service?.close();rmSync(root,{recursive:true,force:true});}});
