/**
 * Notion Reporting Service
 *
 * Prepares data for pushing weekly labor reports to Notion.
 * Pages are created via the Notion MCP tool at the agent layer.
 */
import type { Schedule } from '$lib/types/Schedule';
import type { LaborCostSnapshot, RoleLaborCost } from '$lib/types/LaborCost';
import { formatCurrency, formatPct } from '$lib/utils/labor-math';
import { formatDateShort } from '$lib/utils/date';
import { STAFF_ROLE_LABELS } from '$lib/types/Employee';

export interface NotionReportPage {
  title: string;
  content: string;  // Markdown content for the Notion page
  properties: Record<string, string | number>;
}

/** Build a weekly labor summary report for Notion */
export function buildWeeklyReport(
  weekStartDate: string,
  locationName: string,
  schedule: Schedule | null,
  laborSnapshots: LaborCostSnapshot[],
): NotionReportPage {
  const totalRevenue = laborSnapshots.reduce((s, snap) => s + snap.totalRevenue, 0);
  const totalLaborCost = laborSnapshots.reduce((s, snap) => s + snap.totalLaborCost, 0);
  const totalHours = laborSnapshots.reduce((s, snap) => s + snap.totalHours, 0);
  const overtimeHours = laborSnapshots.reduce((s, snap) => s + snap.overtimeHours, 0);
  const laborPct = totalRevenue > 0 ? totalLaborCost / totalRevenue : 0;
  const cplh = totalHours > 0 ? (totalRevenue / 35) / totalHours : 0; // Estimated covers
  const rplh = totalHours > 0 ? totalRevenue / totalHours : 0;

  // Build daypart summary
  const daypartTotals: Record<string, { hours: number; cost: number; revenue: number }> = {};
  for (const snap of laborSnapshots) {
    for (const dp of snap.byDaypart || []) {
      if (!daypartTotals[dp.daypart]) daypartTotals[dp.daypart] = { hours: 0, cost: 0, revenue: 0 };
      daypartTotals[dp.daypart].hours += dp.hours;
      daypartTotals[dp.daypart].cost += dp.cost;
      daypartTotals[dp.daypart].revenue += dp.revenue;
    }
  }

  const daypartRows = Object.entries(daypartTotals)
    .map(([dp, data]) => {
      const dpPct = data.revenue > 0 ? data.cost / data.revenue : 0;
      return `| ${dp.charAt(0).toUpperCase() + dp.slice(1).replace('_', ' ')} | ${data.hours.toFixed(1)} | ${formatCurrency(data.cost)} | ${formatCurrency(data.revenue)} | ${formatPct(dpPct)} |`;
    })
    .join('\n');

  const content = `# Weekly Labor Report: ${locationName}
## Week of ${formatDateShort(weekStartDate)}

### Summary

| Metric | Value |
|--------|-------|
| Total Revenue | ${formatCurrency(totalRevenue)} |
| Total Labor Cost | ${formatCurrency(totalLaborCost)} |
| Labor Cost % | ${formatPct(laborPct)} |
| Total Hours | ${totalHours.toFixed(1)} |
| Overtime Hours | ${overtimeHours.toFixed(1)} |
| CPLH | ${cplh.toFixed(1)} |
| RPLH | ${formatCurrency(rplh)} |

### Daypart Breakdown

| Daypart | Hours | Labor Cost | Revenue | Labor % |
|---------|-------|-----------|---------|---------|
${daypartRows || '| No data | — | — | — | — |'}

### Schedule Summary

${schedule ? `- Total Shifts: ${schedule.shifts?.length || 0}
- Scheduled Hours: ${schedule.totalScheduledHours?.toFixed(1) || '0'}
- Optimization Score: ${schedule.optimizationScore || 'N/A'}/100
- Status: ${schedule.status}` : 'No schedule data available.'}

---
*Generated by HELIXO — ${new Date().toISOString().split('T')[0]}*`;

  return {
    title: `${locationName} — Labor Report: Week of ${formatDateShort(weekStartDate)}`,
    content,
    properties: {
      'Location': locationName,
      'Week': weekStartDate,
      'Revenue': totalRevenue,
      'Labor Cost': totalLaborCost,
      'Labor %': Math.round(laborPct * 1000) / 10,
      'Hours': totalHours,
      'OT Hours': overtimeHours,
    },
  };
}

/** Build a multi-location comparison report */
export function buildLocationBenchmarkReport(
  weekStartDate: string,
  locationReports: Array<{ locationName: string; revenue: number; laborCost: number; laborPct: number; hours: number; cplh: number }>,
): NotionReportPage {
  const sortedByPct = [...locationReports].sort((a, b) => a.laborPct - b.laborPct);

  const rows = sortedByPct.map((loc, i) => {
    const rank = i + 1;
    const status = loc.laborPct <= 0.28 ? 'On Target' : loc.laborPct <= 0.31 ? 'Warning' : 'Over Budget';
    return `| ${rank} | ${loc.locationName} | ${formatCurrency(loc.revenue)} | ${formatPct(loc.laborPct)} | ${loc.cplh.toFixed(1)} | ${status} |`;
  }).join('\n');

  const totalRevenue = locationReports.reduce((s, l) => s + l.revenue, 0);
  const totalCost = locationReports.reduce((s, l) => s + l.laborCost, 0);
  const avgPct = totalRevenue > 0 ? totalCost / totalRevenue : 0;

  const content = `# Location Benchmark Report
## Week of ${formatDateShort(weekStartDate)}

### Portfolio Summary
- **Locations:** ${locationReports.length}
- **Total Revenue:** ${formatCurrency(totalRevenue)}
- **Total Labor Cost:** ${formatCurrency(totalCost)}
- **Portfolio Labor %:** ${formatPct(avgPct)}

### Rankings (by Labor Cost %)

| Rank | Location | Revenue | Labor % | CPLH | Status |
|------|----------|---------|---------|------|--------|
${rows}

---
*Generated by HELIXO — ${new Date().toISOString().split('T')[0]}*`;

  return {
    title: `Location Benchmark: Week of ${formatDateShort(weekStartDate)}`,
    content,
    properties: {
      'Week': weekStartDate,
      'Locations': locationReports.length,
      'Total Revenue': totalRevenue,
      'Portfolio Labor %': Math.round(avgPct * 1000) / 10,
    },
  };
}
